<?php require_once 'app/views/templates/headerPublic.php'; ?>
<header class="header">
    <h1>Search Movies, Anytime Anywhere.</h1>
    <p class="lead">With SHDb you can search over 20,000 movies, rate them, and generate AI reviews. What are you waiting for?</p>
    <a class="btn btn-secondary btn-lg" href="/create" role="button">Sign Up</a>
</header>
<section class="features container text-center">
    <h3>Why Choose SHDb Movies?</h3>
    <div class="row">
        <div class="col-md-3 feature">
            <i class="bi bi-globe fa-3x"></i>
            <h4>Works Worldwide</h4>
            <p>Search for movies and get AI-generated reviews from anywhere in the world.</p>
        </div>
        <div class="col-md-3 feature">
            <i class="bi bi-film fa-3x"></i>
            <h4>Thousands of Movies</h4>
            <p>Choose from thousands of movies to get reviews and rate them.</p>
        </div>
        <div class="col-md-3 feature">
            <i class="bi bi-star fa-3x"></i>
            <h4>Rate Your Favorites</h4>
            <p>Share your opinion and rate movies to help others discover the best content.</p>
        </div>
        <div class="col-md-3 feature">
            <i class="bi bi-lightbulb fa-3x"></i>
            <h4>AI-Generated Reviews</h4>
            <p>Enjoy detailed and insightful reviews generated by advanced AI technology.</p>
        </div>

    </div>
</section>
<?php require_once 'app/views/templates/footer.php'; ?>

<!-- Include Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
